### ISSUE TITLE
NRFX_ADC_DEFAULT_CHANNEL error: braces around scalar initializer

### ISSUE THREAD

**Issue by jacobrosenthal** [NordicSemiconductor/nrfx#10]
repos/apache-mynewt-core/apps/adc_test/src/main.c:69:5: error: braces around scalar initializer [-Werror]

https://github.com/NordicSemiconductor/nrfx/blob/e168d06a478feae53778060ec0484eece1657377/drivers/include/nrfx_adc.h#L91

I believe this was ported untested from the old nrf51 code and no longer requires extra wrapping braces

**Comment by kl-cruz** [comment]
We have never seen errors like this one. Could You provide a sample code?
ADC driver and hal will be refactored a little in incoming release to have similar API to SAADC one.

**Comment by jacobrosenthal** [comment]
User error, I was assigning it to nrfx_adc_channel_config_t
