### ISSUE TITLE
Erratas higher than 217 are not applied in the system_nrf52.c file

### ISSUE THREAD

**Issue by RR-Rico** [NordicSemiconductor/nrfx#102]
Is there a reason for that? For exmaple why ist 246 not called?

**Comment by nika-nordic** [comment]
Hi @RR-Rico,

Not every errata can be applied in `system_nrf52.c` file as some of them should be used during specific conditions or may introduce unwanted side-effects. Specifically Errata 246 [link](https://infocenter.nordicsemi.com/index.jsp?topic=%2Ferrata_nRF52840_Rev3%2FERR%2FnRF52840%2FRev3%2Flatest%2Fanomaly_840_246.html&cp=4_0_1_0_1_49) introduces extra power consumption which could be unacceptable for some users
