### ISSUE TITLE
Add support for USBD in nrf52.svd

### ISSUE THREAD

**Issue by shilkup** [NordicSemiconductor/nrfx#103]
It seems that USBD (base address 0x40027000) peripheral is missing from the nrf52.svd. It would be a great help with debugging.

**Comment by nika-nordic** [comment]
Hi @shilkup ,

nRF52832 device (which is associated with `nrf52.svd` file you mention) does not contain USBD peripheral. The address `0x40027000` is present on nRF52840, which is a different device ([link](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf52840%2Fusbd.html&cp=4_0_0_5_34_12&anchor=topic))
