### ISSUE TITLE
Incorrect workaround for nRF53 anomaly 161

### ISSUE THREAD

**Issue by sw** [NordicSemiconductor/nrfx#112]
`nrf_reset_network_force_off` uses `nrf53_errata_161` to decide if the workaround for [anomaly 161](https://infocenter.nordicsemi.com/topic/errata_nRF5340_Rev1/ERR/nRF5340/Rev1/latest/anomaly_340_161.html) is needed:
https://github.com/NordicSemiconductor/nrfx/blob/1c721175f22dbb1bf125a570a427b53f810881bb/hal/nrf_reset.h#L175-L187

However that function only returns `true` when compiled for the network core:
https://github.com/NordicSemiconductor/nrfx/blob/1c721175f22dbb1bf125a570a427b53f810881bb/mdk/nrf53_erratas.h#L5876-L5909

**Comment by nika-nordic** [comment]
hi @sw ,

Thank you for reporting this issue. We are already processing it internally. General plan is to provide updated MDK that next nrfx should contain
