### ISSUE TITLE
nrfx: mdk: missing `nrf52832.svd`

### ISSUE THREAD

**Issue by JordanYates** [NordicSemiconductor/nrfx#114]
There is no `nrf52832.svd` file in the `nrfx/mdk` folder, which is unexpected given that all other microcontrollers seem to be represented.
```
user@comp mdk % ls *.svd
nrf51.svd		nrf52810.svd		nrf52833.svd		nrf5340_network.svd
nrf52.svd		nrf52811.svd		nrf52840.svd		nrf9160.svd
nrf52805.svd		nrf52820.svd		nrf5340_application.svd
```

**Comment by awojasinski-nordicsemi** [comment]
Hi @JordanYates,

nRF52832 was the first chip of the 52 series and is so old that there were assumptions that there were only going to be a need for one svd file for the family. This we now know is wrong, but the svd file is named `nrf52.svd` because of this.

Hope that resolves the issue
