### ISSUE TITLE
'doc/html' missing: readme edit suggestion 

### ISSUE THREAD

**Issue by neekonsu** [NordicSemiconductor/nrfx#119]
This should be quick, I noticed that the readme points to `doc/html` for more information, but there is no html folder in doc. Please add the html or remove that instruction as it's not current. Thanks.

**Comment by nika-nordic** [comment]
hello,

`html` directory will appear once this script: https://github.com/NordicSemiconductor/nrfx/blob/master/doc/generate_html_doc.sh is invoked
