### ISSUE TITLE
Bug in include path

### ISSUE THREAD

**Issue by ciankc** [NordicSemiconductor/nrfx#120]
Include path bug prevents nrfx_saadc from being used. 

https://github.com/NordicSemiconductor/nrfx/blob/7c47cc0a56ce44658e6da2458e86cd8783ccc4a2/drivers/include/nrfx_saadc.h#L38

**Comment by nika-nordic** [comment]
Hello,

this code should work provided that `nrfx` root directory is added to compiler inclusion paths, which is something expected by all of the `nrfx` drivers
