### ISSUE TITLE
Error in nrfx_ppi makes logging in nrf5 sdk context impossible

### ISSUE THREAD

**Issue by nordic-krch** [NordicSemiconductor/nrfx#21]
https://github.com/NordicSemiconductor/nrfx/blob/c6ba99f45bc24e15bd2198137d2eb8a8fdef250c/drivers/src/nrfx_ppi.c#L38

Line should be changed to:
#define NRFX_LOG_MODULE PPI

**Comment by kl-cruz** [comment]
Will be fixed in next release

**Comment by kl-cruz** [comment]
Fixed in 1.1.0 : https://github.com/NordicSemiconductor/nrfx/blob/master/drivers/src/nrfx_ppi.c#L38
