### ISSUE TITLE
ARRAY_SIZE is not defined

### ISSUE THREAD

**Issue by hathach** [NordicSemiconductor/nrfx#37]
nrf_power (and some other files) check for `ARRAY_SIZE` but it is only defined in sdk files. 

```
__STATIC_INLINE void nrf_power_rampower_mask_on(uint8_t block, uint32_t section_mask)
{
    NRFX_ASSERT(block < ARRAY_SIZE(NRF_POWER->RAM));
    NRF_POWER->RAM[block].POWERSET = section_mask;
}
```

It should be in nrfx_glues or locally defined to decouple nrfx and sdk

```
#ifndef ARRAY_SIZE
#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))
#endif
```

**Comment by kl-cruz** [comment]
Hi,
That's right. Thank you for opening this issue! We fixed it in the newest release:
https://github.com/NordicSemiconductor/nrfx/blob/master/drivers/nrfx_common.h#L139
https://github.com/NordicSemiconductor/nrfx/blob/master/hal/nrf_power.h#L969
