### ISSUE TITLE
NRFX_CHECK(NRFX_FOO_ENABLED)

### ISSUE THREAD

**Issue by SebastianBoe** [NordicSemiconductor/nrfx#41]
nrfx should not be using source code guards like #ifdef NRFX_CHECK(NRFX_FOO_ENABLED).

Instead build systems should be including or excluding whole source files in the build.

**Comment by SebastianBoe** [comment]
FYI: @anangl

**Comment by nika-nordic** [comment]
`NRFX_CHECK(NRFX_FOO_ENABLED)` does not stop the user from including or excluding only specific files in the build. For example in the Zephyr RTOS this is exactly how it is done - driver source files are included in the build only if associated Kconfig symbol is set: https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/hal_nordic/nrfx/CMakeLists.txt#L64-L97

**Comment by SebastianBoe** [comment]
I was not arguing that it would prevent users from using the build system for this purpose.

I am arguing that in no circumstance should whole source files be if-def'd out with the preprocessor. So we should remove the ifdef.

Ifdef'ing out with the preprocessor slows down the build as gcc still needs to be invoked per-source file.

It also causes noise in the logs, as users can see that the adc driver is being compiled even though it's application does not use adc for instance.

We should drop support for ifdef'ing out whole source files.
