### ISSUE TITLE
nrfx_uarte.h - incorrect size in nrfx_uarte_xfer_evt_t

### ISSUE THREAD

**Issue by PeterKenyon** [NordicSemiconductor/nrfx#44]
The structure nrfx_uarte_xfer_evt_t has a member bytes which is only 8 bits this should be a uint16_t to support NRF52840

**Comment by kl-cruz** [comment]
Hi,
I see issue in https://github.com/NordicSemiconductor/nrfx/blob/master/drivers/include/nrfx_uarte.h#L125 . Thank you for this. It has to be fixed

**Comment by kl-cruz** [comment]
Fixed in new version:
https://github.com/NordicSemiconductor/nrfx/blob/master/drivers/include/nrfx_uarte.h#L125
