### ISSUE TITLE
nrfx_qspi.h non C++ friendly initialialiser

### ISSUE THREAD

**Issue by PeterKenyon** [NordicSemiconductor/nrfx#45]
nrfx_qspi.h has a C++ guard but then uses an NRFX_QSPI_DEFAULT_CONFIG initialiser with out of order definitions, this is not C++ friendly and easily fixed, just initialise the structure in the correct order

**Comment by kl-cruz** [comment]
Hi, That's right. We have created internal task to handle it. It will be fixed in one of the future releases.

**Comment by kl-cruz** [comment]
Fixed in 1.7.0:
https://github.com/NordicSemiconductor/nrfx/commit/ab87d03dcfa9ddf78c8f86d977be12f0c80eb37b#diff-ba8ed158826ab1896c7603405c2c43a6R81
Thank you!
