### ISSUE TITLE
nrfx_gpiote: loss of level detection interrupts

### ISSUE THREAD

**Issue by pabigot** [NordicSemiconductor/nrfx#48]
zephyrproject-rtos/zephyr#11806 identifies an error in processing the GPIOTE `PORT` event that can cause sense changes to be lost because the rising edge of `DETECT` was not captured.  The same problem appears to be present in nrfx through 1.4.0.

Consider the following execution of [`nrfx_gpiote_irq_handler`](https://github.com/NordicSemiconductor/nrfx/blob/595e79f63f21224f6a42325095be9940a4a62ffb/drivers/src/nrfx_gpiote.c#L684):

On entry the PORT event is set.  The implementation captures the pins, and clears the event.  The `DETECT` signal remains asserted.

All that is necessary for the failure to occur is a run through the rest of the function that exits with `repeat` false while the `DETECT` signal is never deasserted.  The following sequences reaches this state:

* Assume that SENSE is asserted for GPIO pins 0 and 31.  Between the point the ISR is entered and the check for pin state of GPIO 0 the input of pin 0 changes so its SENSE is no longer asserted.  DETECT remains asserted due to pin 31.  The mismatch in sense means `repeat` is not incremented for pin 0.
* Between checking pin 0 and pin 31 pin 0 changes state again, so that its SENSE signal is asserted; after this pin 31 changes state so its SENSE signal is deasserted.  DETECT remains asserted at all times, but the test for pin 31 succeeds and `repeat` is not incremented.

At the bottom of the loop `repeat` is zero so the ISR exits.  The `PORT` event has been cleared, and `DETECT` remains asserted.  No further level interrupts will be signalled.

An real-world application where level can change without any application control like this is monitoring dry contacts, a situation perfectly suited to level detection and where a device may have more inputs than there are edge detection resources on the chip.

**Comment by nika-nordic** [comment]
`PORT` event handling has been improved in `nrfx_gpiote` driver refactor in nrfx 2.6.0
