### ISSUE TITLE
NFCT RX/TX example

### ISSUE THREAD

**Issue by hdkim** [NordicSemiconductor/nrfx#60]
I want to write a library to emulate a nfc tag without t2t and t4t NRF library.

so now, I am using nrfx_nfct library directly. but there is a problem.

To demonstrate how to work the t4t library, I write logs on all function in nrfx_nfct.c file.
Because t4t library also use the core nrfx_nfct library.

when I use t4t library, it work correctly.
it work in correct sequence RX -> TX -> RX.
you can check the RX ended event and TX ended event below logs 

---------- t2t library logs ----------
Selected
rxtx enable mask:0460
RX start- size:256, data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
RX Frame End
rxtx enable mask:0018
TX start- delay mode: NRF_NFCT_FRAME_DELAY_MODE_WINDOWGRID, size:5, data:05 78 80 42 02 
TX Frame End
rxtx enable mask:0460
RX start- size:256, data:e0 81 b8 62 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
RX Frame End
rxtx enable mask:0460
RX start- size:256, data:0a 01 00 ca 01 01 08 60 42 00 00 00 00 00 00 00 00 00 00 00 
rxtx enable mask:0018
TX start- delay mode: NRF_NFCT_FRAME_DELAY_MODE_EXACTVAL, size:3, data:fa 01 08
-------------------------------------------------------------------------------------------
But When I write a code by using only nrfx_nfct and receive event and RX/TX by myself.

the TX ended event never be called.

when I do tx, it always return RX ended event.

is there any other config? or something that i missed?

---------- nrfx_nfct logs ------------
Selected
nfct event : NRFX_NFCT_EVT_SELECTED
rxtx enable mask:0460
RX start- size:256, data:00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 53 45 
RX Frame End
nfct event : NRFX_NFCT_EVT_RX_FRAMEEND
receive RATS, DID:1, FSD:0
rxtx enable mask:0018
TX start- delay mode: NRF_NFCT_FRAME_DELAY_MODE_WINDOWGRID, size:5, data:05 78 80 42 02 
RX Frame End
nfct event : NRFX_NFCT_EVT_RX_FRAMEEND
-------------------------------------------------------------------------------------------

**Comment by kapi-no** [comment]
Well, I think it is an issue with the driver configuration. Try initializing the driver with NRF_NFCT_INT_TXFRAMEEND_MASK to enable "TX Frame End" callback.

    nrfx_nfct_config_t config =
    {
        .rxtx_int_mask = (NRF_NFCT_INT_RXFRAMEEND_MASK   | 
                                    NRF_NFCT_INT_RXERROR_MASK      | 
                                    NRF_NFCT_INT_TXFRAMESTART_MASK | 
                                    NRF_NFCT_INT_TXFRAMEEND_MASK),
        (...)
    };
