### ISSUE TITLE
Quetion: Release date of nRF5 SDK compatible with nrfx v2.2.0

### ISSUE THREAD

**Issue by hubpav** [NordicSemiconductor/nrfx#73]
Hi, when do you expect to release nRF5 SDK compatible with nrfx v2.2.0 release, please?

**Comment by kl-cruz** [comment]
Hi! 
There is no plan to support nrfx 2.x branch in the nRF5 SDK. You can use nRF Connect SDK instead, to work with the newest nrfx release. Find more at: https://www.nordicsemi.com/Software-and-tools/Software/nRF-Connect-SDK
