### ISSUE TITLE
`nrf9160.svd` is malformed

### ISSUE THREAD

**Issue by jonas-schievink** [NordicSemiconductor/nrfx#92]
The SVD file for the nRF9160 (https://github.com/NordicSemiconductor/nrfx/blob/master/mdk/nrf9160.svd) contains 3 errors:

In lines 628, 635, and 4841, a register access value of `read-writeonce` is specified, but it should be `read-writeOnce`, with an uppercase O.

The valid access types are specified at the bottom of this page: https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_special.html#elem_access

**Comment by nika-nordic** [comment]
Hi @jonas-schievink ,

thank you for raising this issue. We will look into this

**Comment by nika-nordic** [comment]
Hi again @jonas-schievink 

looks like there is a bug in our .svd file creation process. The fix should be available in next release. Thank you again for reporting this

**Comment by jonas-schievink** [comment]
Thanks for the quick response!

**Comment by nika-nordic** [comment]
New nrfx release 2.6.0 contains updated MDK. Closing
