### ISSUE TITLE
Full support for nRF9160 (at least to nRF52840 'level')

### ISSUE THREAD

**Issue by jwest247** [NordicSemiconductor/nrfx#98]
Hello All,

First - thank all of you that are involved in this effort and maintaining this repository on github for the rest of us to use.

I have a request - after looking here:
https://infocenter.nordicsemi.com/index.jsp?topic=%2Fdrivers_nrfx_v2.7.0%2Findex.html

The far right hand column has the nRF9160.

And, there's quite a list of unsupported features(thus far):

The most important (obviously):  RADIO.

Support for UART, and SPI also have 'x's'.  

So, the question here is - when will the nRF9160 be as fully supported as the nRF52840?  
Can you give an estimate as to when that will happen?

I realize there are some M33 issues that don't pertain to the M4 on the nRF52840 - but key features like RADIO, SPI, and UART are worth knowing about as to when they will be supported.

Thanks In Advance,
jwest247

**Comment by nika-nordic** [comment]
Hi @jwest247,

First of all - thank you for the appreciation!

Answering you questions:
- RADIO peripheral will be never supported in `nrfx` as nRF9160 contains LTE modem which is completely different than nRF52840 ([link](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf9160%2Fip%2Fradio_lte%2Fdoc%2Ffrontpage.html))
- nRF9160 does not contain SPI or UART, however there are SPIM and UARTE available, which are basically SPI/UARTE but with DMA engine. They can be used instead and are more efficient.
